language: objective-c
osx_image: xcode10.2
xcode_project: Sample.xcodeproj
xcode_scheme: Sample
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
script:
  - set -o pipefail && xcodebuild -project Sample.xcodeproj -scheme Sample -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPhone\ X build test | xcpretty